### ISSUE TITLE
대화창

### ISSUE THREAD

**Issue by geon-jegal** [Corew2/PROJECT-MOD#1]
블랙 헤븐 대화창 제작 완료
- 글자가 하나씩 나오게 해야됨

**Comment by geon-jegal** [comment]
npc에 2개 이상의 퀘스트가 있는 경우
-> 서브 퀘스트 창으로 2개 이상의 퀘스트 출력
-> 유저가 선택
-> 메인 퀘스트면 대화창을 메인 대화 창으로 전환
-> 퀘스트 실행 
-------------------------------------------------------------------
- 모든 npc에 서브 퀘스트 컴포넌트가 있어야함
- 스토리 진행도에 따라 각 퀘스트의 수행 여부를 데이터에 추가(또는 테이블로 추가)

**Comment by henac290** [comment]
- 대화 Component를 QuestLogic으로 변경
- QuestLogic(Main, Sub구분),
  QuestComponent,
  QuestButtonComponent,
  UiPanelTable,
  QuestTable 사용
- UISpriteComponent(대화창 이미지 고정),
  SetPlayerCtrl(플레이어 움직임 통제)사용
